### PR TITLE
Create hello world.pseudo file

### PR DESCRIPTION
**Pull request by ninjagolloyd**
Another file extension

### CODE REVIEW

**Comment by TropicSapling** [comment]
Huh?

**Comment by ninjagolloyd** [comment]
#2 look

**Comment by ninjagolloyd** [comment]
Corresponds to #2

**Comment by ninjagolloyd** [comment]
Fixed and added .pb

**Comment by TropicSapling** [comment]
Sorry a conflict appeared, try creating a new pull request :)

**Pull request closed without merging**
