### PR TITLE
Update compiler.py

### PR DESCRIPTION
**Pull request by ninjagolloyd**
Now supports .pseudo as an extension

### CODE REVIEW

**Comment by TropicSapling** [comment]
Huh? PBTL is a programming language, and one programming language not several ones?

**Comment by ninjagolloyd** [comment]
It is an extension. It is just another file name, not another language. Try it.

**Comment by TropicSapling** [comment]
Yes but what does that extension have to do with this language? What if someone writes Python code in a .pseudo file? That will just cause lots of errors...

**Comment by ninjagolloyd** [comment]
Yes, but if they write PBTL in a pseudo file it will work. Kinda like C++. It has .c .cpp and a few others and they give the same output.

**Comment by ninjagolloyd** [comment]
My point is they both compile to .py. Try it; you will find it works.

**Comment by ninjagolloyd** [comment]
Oh... Now I see what I did wrong. X(

**Comment by TropicSapling** [comment]
Yes but I don't see why this would be useful? It would just make things confusing...

**Comment by ninjagolloyd** [comment]
Some people like different names xD

**Comment by TropicSapling** [comment]
Hmm well if so it should more like be something similar to the language, like .pbl, .pbpl or .pbtpl

**Comment by ninjagolloyd** [comment]
Ok

**Comment by ninjagolloyd** [comment]
Changed .pseudo to .pb and fixed and expression

**Comment by TropicSapling** [comment]
I would still recommend .pbl since pb stands for "python based" so it could be anything python based. But I'll merge this now anyway :)

**Pull request merged**
